/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import App.ClientMainFrame;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author mertcankarabas
 */
public class Emoji extends javax.swing.JFrame {

    /**
     * Creates new form testtt
     */
    ClientMainFrame mainFrame;

    public Emoji(ClientMainFrame mainFrame) {
        initComponents();       
        this.mainFrame = mainFrame;
        init();
    }

    private void init() {
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(200, 230));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setSize(new java.awt.Dimension(200, 200));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton1.setText("😀");
        jButton1.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton2.setText("😄");
        jButton2.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton3.setText("😅");
        jButton3.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton4.setText("😂");
        jButton4.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton5.setText("🥲");
        jButton5.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton6.setText("😊");
        jButton6.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton7.setText("😇");
        jButton7.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton7.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton8.setText("🙂");
        jButton8.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton8.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton8.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton9.setText("😉");
        jButton9.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton9.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton9.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton10.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton10.setText("🥰");
        jButton10.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton10.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton10.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton11.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton11.setText("😘");
        jButton11.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton11.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton11.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton12.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton12.setText("😛");
        jButton12.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton12.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton12.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton13.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton13.setText("😜");
        jButton13.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton13.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton13.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton14.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton14.setText("😎");
        jButton14.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton14.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton14.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);

        jButton15.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton15.setText("😏");
        jButton15.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton15.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton15.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton16.setText("😒");
        jButton16.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton16.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton16.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton17.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton17.setText("😔");
        jButton17.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton17.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton17.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);

        jButton18.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton18.setText("😕");
        jButton18.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton18.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton18.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);

        jButton19.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton19.setText("🙁");
        jButton19.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton19.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton19.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);

        jButton20.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton20.setText("😣");
        jButton20.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton20.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton20.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);

        jButton21.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton21.setText("🤫");
        jButton21.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton21.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton21.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);

        jButton22.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton22.setText("😐");
        jButton22.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton22.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton22.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);

        jButton23.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton23.setText("👍");
        jButton23.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton23.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton23.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);

        jButton24.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton24.setText("👎");
        jButton24.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton24.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton24.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);

        jButton25.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton25.setText("👊");
        jButton25.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton25.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton25.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);

        jTabbedPane1.addTab("Smile", jPanel1);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        jPanel3.setLayout(new java.awt.GridLayout(5, 5));

        jButton26.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton26.setText("🐶");
        jButton26.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton26.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton26.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton26);

        jButton27.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton27.setText("🐱");
        jButton27.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton27.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton27.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton27);

        jButton28.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton28.setText("🐭");
        jButton28.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton28.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton28.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton28);

        jButton29.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton29.setText("🐹");
        jButton29.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton29.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton29.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton29);

        jButton30.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton30.setText("🐰");
        jButton30.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton30.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton30.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton30);

        jButton31.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton31.setText("🦊");
        jButton31.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton31.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton31.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton31);

        jButton32.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton32.setText("🐻");
        jButton32.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton32.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton32.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton32);

        jButton33.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton33.setText("🐼");
        jButton33.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton33.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton33.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton33);

        jButton34.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton34.setText("🐨");
        jButton34.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton34.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton34.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton34);

        jButton35.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton35.setText("🐯");
        jButton35.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton35.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton35.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton35);

        jButton36.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton36.setText("🦁");
        jButton36.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton36.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton36.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton36);

        jButton37.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton37.setText("🐮");
        jButton37.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton37.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton37.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton37);

        jButton38.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton38.setText("🐷");
        jButton38.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton38.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton38.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton38);

        jButton39.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton39.setText("🐵");
        jButton39.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton39.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton39.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton39);

        jButton40.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton40.setText("🙈");
        jButton40.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton40.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton40.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton40);

        jButton41.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton41.setText("🙉");
        jButton41.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton41.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton41.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton41);

        jButton42.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton42.setText("🙊");
        jButton42.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton42.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton42.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton42);

        jButton43.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton43.setText("🐒");
        jButton43.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton43.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton43.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton43);

        jButton44.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton44.setText("🐣");
        jButton44.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton44.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton44.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton44);

        jButton45.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton45.setText("🐥");
        jButton45.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton45.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton45.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton45);

        jButton46.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton46.setText("🔥");
        jButton46.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton46.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton46.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton46);

        jButton47.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton47.setText("🌑");
        jButton47.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton47.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton47.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton47);

        jButton48.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton48.setText("🌙");
        jButton48.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton48.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton48.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton48);

        jButton49.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton49.setText("💫");
        jButton49.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton49.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton49.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton49);

        jButton50.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jButton50.setText("🌊");
        jButton50.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton50.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton50.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton50);

        jTabbedPane1.addTab("Animals", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JTextField txt_message = mainFrame.getTxt_message();
        txt_message.setText(txt_message.getText() + ((JButton)evt.getSource()).getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emoji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Emoji().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
