/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Server;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author mertcankarabas
 */
public class Server_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Server_Frame
     */
    Server server;
    int port;
    public static DefaultListModel lst_client_model = new DefaultListModel();
    public Server_Frame() {
        initComponents();
        this.lst_clients.setModel(lst_client_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_port = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_clients = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txt_sendBoradcast = new javax.swing.JTextField();
        btn_boradcast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Port");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 49, 23, 17);
        getContentPane().add(txt_port);
        txt_port.setBounds(96, 46, 64, 23);

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start);
        btn_start.setBounds(33, 87, 72, 23);

        btn_stop.setText("Stop");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stop);
        btn_stop.setBounds(123, 87, 72, 23);

        jScrollPane2.setViewportView(lst_clients);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(273, 46, 203, 130);

        jLabel2.setText("Clients");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(287, 23, 40, 17);
        getContentPane().add(txt_sendBoradcast);
        txt_sendBoradcast.setBounds(280, 220, 190, 23);

        btn_boradcast.setText("Broadcast");
        btn_boradcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boradcastActionPerformed(evt);
            }
        });
        getContentPane().add(btn_boradcast);
        btn_boradcast.setBounds(280, 260, 140, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        port = Integer.parseInt(txt_port.getText());
        try {
            server = new Server(port);
            server.StartServer();
        } catch (IOException ex) {
            Logger.getLogger(Server_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        try {
            // TODO add your handling code here:,
            this.server.StopServer();
        } catch (IOException ex) {
            Logger.getLogger(Server_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_stopActionPerformed

    private void btn_boradcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boradcastActionPerformed
        // TODO add your handling code here:
        this.server.sendBroadcast(txt_sendBoradcast.getText());
    }//GEN-LAST:event_btn_boradcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boradcast;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_clients;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_sendBoradcast;
    // End of variables declaration//GEN-END:variables
}
