/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Forms.ComponentResizer;
import Forms.People;
import Forms.ScrollBar;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author mertcankarabas
 */
public class Login extends javax.swing.JFrame {
    
    boolean isTypeName = false;
    
    
    /**
     * Creates new form ServerMainFram
     */
    public Login() {
        initComponents();
        init();

    }

    
    
    private void init() {
        ComponentResizer compRes = new ComponentResizer();
        compRes.registerComponent(this);
        compRes.setMinimumSize(new Dimension(800, 500));
        compRes.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        compRes.setSnapSize(new Dimension(10, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header = new javax.swing.JPanel();
        pnl_closeMaxMin = new javax.swing.JPanel();
        pnl_max = new javax.swing.JPanel();
        lbl_max = new javax.swing.JLabel();
        pnl_close = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        pnl_chatBackground = new javax.swing.JPanel();
        pnl_logo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        pnl_giris = new javax.swing.JPanel();
        lbl_enterName = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_enter = new javax.swing.JButton();
        lbl_warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnl_header.setBackground(new java.awt.Color(0, 100, 102));
        pnl_header.setPreferredSize(new java.awt.Dimension(800, 30));
        pnl_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_headerMouseDragged(evt);
            }
        });
        pnl_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_headerMousePressed(evt);
            }
        });
        pnl_header.setLayout(new java.awt.BorderLayout());

        pnl_closeMaxMin.setBackground(new java.awt.Color(0, 100, 102));
        pnl_closeMaxMin.setPreferredSize(new java.awt.Dimension(60, 30));
        pnl_closeMaxMin.setSize(new java.awt.Dimension(100, 30));
        pnl_closeMaxMin.setLayout(null);

        pnl_max.setBackground(new java.awt.Color(0, 100, 102));

        lbl_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_max.setIcon(new javax.swing.ImageIcon("/Users/mertcankarabas/NetBeansProjects/IletisimClient/src/main/java/Icons/Full_Screen_Button.png")); // NOI18N
        lbl_max.setPreferredSize(new java.awt.Dimension(30, 30));
        lbl_max.setSize(new java.awt.Dimension(30, 30));
        lbl_max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_maxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_maxLayout = new javax.swing.GroupLayout(pnl_max);
        pnl_max.setLayout(pnl_maxLayout);
        pnl_maxLayout.setHorizontalGroup(
            pnl_maxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_maxLayout.createSequentialGroup()
                .addComponent(lbl_max, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_maxLayout.setVerticalGroup(
            pnl_maxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_max, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnl_closeMaxMin.add(pnl_max);
        pnl_max.setBounds(0, 0, 30, 0);

        pnl_close.setBackground(new java.awt.Color(0, 100, 102));

        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setIcon(new javax.swing.ImageIcon("/Users/mertcankarabas/NetBeansProjects/IletisimClient/src/main/java/Icons/Close_Button.png")); // NOI18N
        lbl_close.setPreferredSize(new java.awt.Dimension(30, 30));
        lbl_close.setSize(new java.awt.Dimension(30, 30));
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_closeLayout = new javax.swing.GroupLayout(pnl_close);
        pnl_close.setLayout(pnl_closeLayout);
        pnl_closeLayout.setHorizontalGroup(
            pnl_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_closeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_closeLayout.setVerticalGroup(
            pnl_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnl_closeMaxMin.add(pnl_close);
        pnl_close.setBounds(30, 0, 30, 0);

        pnl_header.add(pnl_closeMaxMin, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnl_header, java.awt.BorderLayout.PAGE_START);

        pnl_chatBackground.setBackground(new java.awt.Color(144, 224, 239));
        pnl_chatBackground.setLayout(new java.awt.BorderLayout());

        pnl_logo.setBackground(new java.awt.Color(144, 224, 239));
        pnl_logo.setPreferredSize(new java.awt.Dimension(400, 470));
        pnl_logo.setLayout(new java.awt.BorderLayout());

        lbl_logo.setBackground(new java.awt.Color(144, 224, 239));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnl_logo.add(lbl_logo, java.awt.BorderLayout.CENTER);

        pnl_chatBackground.add(pnl_logo, java.awt.BorderLayout.LINE_START);

        pnl_giris.setBackground(new java.awt.Color(144, 224, 239));
        pnl_giris.setLayout(null);

        lbl_enterName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_enterName.setText("Enter Name");
        pnl_giris.add(lbl_enterName);
        lbl_enterName.setBounds(113, 193, 170, 30);

        txt_name.setText("Type a name...");
        txt_name.setToolTipText("Type a name...");
        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_nameMouseExited(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });
        pnl_giris.add(txt_name);
        txt_name.setBounds(113, 229, 170, 40);

        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        pnl_giris.add(btn_enter);
        btn_enter.setBounds(113, 287, 170, 40);
        pnl_giris.add(lbl_warning);
        lbl_warning.setBounds(120, 340, 160, 30);

        pnl_chatBackground.add(pnl_giris, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_chatBackground, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    private int pX;
    private int pY;
    private void pnl_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headerMouseDragged
        // TODO add your handling code here:        
        this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_pnl_headerMouseDragged

    private void pnl_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headerMousePressed
        // TODO add your handling code here:
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_pnl_headerMousePressed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseEntered
        // TODO add your handling code here:
        changeColor(pnl_close, new Color(6, 90, 96));
    }//GEN-LAST:event_lbl_closeMouseEntered

    private void lbl_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseExited
        // TODO add your handling code here:
        changeColor(pnl_close, new Color(0, 100, 102));
    }//GEN-LAST:event_lbl_closeMouseExited

    private void lbl_maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_maxMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != Login.MAXIMIZED_BOTH) {
            this.setExtendedState(Login.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(Login.NORMAL);
        }
    }//GEN-LAST:event_lbl_maxMouseClicked

    private void lbl_maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_maxMouseEntered
        // TODO add your handling code here:
        changeColor(pnl_max, new Color(6, 90, 96));
    }//GEN-LAST:event_lbl_maxMouseEntered

    private void lbl_maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_maxMouseExited
        // TODO add your handling code here:
        changeColor(pnl_max, new Color(0, 100, 102));
    }//GEN-LAST:event_lbl_maxMouseExited

    private void txt_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMouseEntered
        // TODO add your handling code here:
        if (!isTypeName) {
            txt_name.setText("");
        }
    }//GEN-LAST:event_txt_nameMouseEntered

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
        // TODO add your handling code here:
        isTypeName = true;
    }//GEN-LAST:event_txt_nameKeyTyped

    private void txt_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMouseExited
        // TODO add your handling code here:
        if (txt_name.getText().equals("")) {
            txt_name.setText("Type a name...");
            isTypeName = false;
        }
    }//GEN-LAST:event_txt_nameMouseExited

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        // TODO add your handling code here:
        
        if (!txt_name.getText().equals("Type a name...")) {
            
            ClientMainFrame newFrame = new ClientMainFrame(txt_name.getText());
            //ClientMainFrame newFrame = new ClientMainFrame();
            newFrame.setVisible(true);
            this.dispose();
        } else {
            lbl_warning.setText("Please enter a name!");
            lbl_warning.setForeground(new Color(255, 0, 0));
        }
        

    }//GEN-LAST:event_btn_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_enterName;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_max;
    private javax.swing.JLabel lbl_warning;
    private javax.swing.JPanel pnl_chatBackground;
    private javax.swing.JPanel pnl_close;
    private javax.swing.JPanel pnl_closeMaxMin;
    private javax.swing.JPanel pnl_giris;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_logo;
    private javax.swing.JPanel pnl_max;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
